project:
  type: website
  output-dir: docs

website:
  title: "Blackout Analysis"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "About"
      - href: geospatial.qmd
        text: "Geospatial Analysis"
      - href: stats.qmd
        text: "Statistical Analysis"
    right:
      - icon: github
        href: https://github.com/marierivers/blackout_analysis
        aria-label: GitHub
    page-footer: "website created with [Quarto](https://quarto.org/) by RStudio"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

