project:
  type: website
  output-dir: docs

website:
  title: "Blackout Analysis"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Geospatial Analysis"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

